apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "appstudio, hacbs"
  name: summary
spec:
  description: >-
    Summary Pipeline Task. Prints PipelineRun information, removes image repository secret used by the PipelineRun.
  params:
    - name: pipelinerun-name
      description: pipeline-run to annotate
    - name: git-url
      description: Git URL
    - name: image-url
      description: Image URL
    - name: build-task-status
      description: State of build task in pipelineRun
      # Default Succeeded for backward compatibility
      default: Succeeded
  steps:
    - name: appstudio-summary
      image: registry.access.redhat.com/ubi9/ubi-minimal:9.2-750.1697625013@sha256:b40f52aa68b29634ff45429ee804afbaa61b33de29ae775568933c71610f07a4
      env:
        - name: GIT_URL
          value: $(params.git-url)
        - name: IMAGE_URL
          value: $(params.image-url)
        - name: PIPELINERUN_NAME
          value: $(params.pipelinerun-name)
        - name: BUILD_TASK_STATUS
          value: $(params.build-task-status)
      script: |
        #!/usr/bin/env bash
        echo
        echo "Build Summary:"
        echo
        echo "Build repository: $GIT_URL"
        if [ "$BUILD_TASK_STATUS" == "Succeeded" ]; then
          echo "Generated Image is in : $IMAGE_URL"
        fi
        echo
        echo End Summary
